services:
  simpleblog:
    build: .
    depends_on:
      - postgresdb
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure

  postgresdb:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: simple_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - simpleblog